### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by tarulyadav** [chankan/SmartKanteen#11]
As a user, I should be able to register to the application

T020	Create User Bean
T021	Create Enum Roles - User, Admin, SuperAdmin
T022	Create service to add user
T023	Create web service to add users

**Comment by tarulyadav** [comment]
Files - User, UserDetails, Role, UserService, UserDAO
Story Status - Completed 80% (Business Layer completed 100%, Web Service - In Progress)

**Comment by chankan** [comment]
Development is done from UI and integration point.
