### ISSUE TITLE
Place Order as User

### ISSUE THREAD

**Issue by tarulyadav** [chankan/SmartKanteen#16]
As a user, I should be able to order items from Daily Menu. I should also be able to view my orders.

T028	Create Order and Order_Details Table
T029	Create Order bean
T030	Create services to place order
T031	Create web-service for placing order
T032	Create filters to fetch orders for user by date

**Comment by tarulyadav** [comment]
Files - OrderService, OrderDAO
Story Status - Completed 80% (Business Layer completed 100%, Web-Service Pending)

**Comment by Harshad12250** [comment]
Files - OrderServiceImpl, OrderDao
Story Status - added method to find OrderById.

**Comment by Harshad12250** [comment]
Files -OrderResource, IOrderResource
Story Status - Development for this functionality completed 100% (including web-service layer). Manual Testing also conducted successfully.
