### ISSUE TITLE
Cancel Order as User

### ISSUE THREAD

**Issue by tarulyadav** [chankan/SmartKanteen#17]
As a user, I should be able to cancel placed orders of today + future dates

T033	Create service to cancel orders of today + future dates
T034	Create web-service for canceling orders

**Comment by Harshad12250** [comment]
In addition to cancellation of an order, Remarks to be added for the reason of Cancellation.

**Comment by Harshad12250** [comment]
Also, details to be captured regarding which User is cancelling the Order (User/Admin).

**Comment by Harshad12250** [comment]
Files updated : OrderMaster, OrderDao, IOrderResource, OrderResource, OrderService, OrderServiceImpl.
Status : 80% done. Cancel Order functionality implemented at service, DAO and web-service layer, capturing orderId, remarks and the user who has cancelled the order.
Extra attribute added to OrderMaster class for capturing the details of the User who is cancelling the order. Testing pending.

**Comment by Harshad12250** [comment]
Story Status : Cancel Order functionality for user, 100% completed including service, DAO and web-service layer. Testing conducted on the same successfully.
