### ISSUE TITLE
As a user I should be able to see UI Menu properly  aligned 

### ISSUE THREAD

**Issue by vaibhavk3** [chankan/SmartKanteen#2]
![ui_issue](https://cloud.githubusercontent.com/assets/10056520/5393414/9d0d77a6-8157-11e4-8ff3-b3b4ecf00fc9.jpg)
Menu Items added should be properly aligned.

**Comment by chankan** [comment]
Done.. Since we don't have constant content it was not getting aligned. Now there will be always two line space for menu header.
